image: Visual Studio 2022

branches:
  except:
  - /^experimental.*$/

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - dotnet --info

build_script:
  - dotnet build Aqua.GraphCompare.sln

test_script:
  - dotnet test test\Aqua.GraphCompare.Tests
