language: generic  

branches:
  except:
  - experimental

addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      env: FRAMEWORK_VERSION=1.0 CLI_VERSION=1.1.5 CONFIGURATION=Release
    - os: linux
      env: FRAMEWORK_VERSION=2.0 CLI_VERSION=2.0.0 CONFIGURATION=Release
    - os: linux
      env: FRAMEWORK_VERSION=2.0 CLI_VERSION=Latest CONFIGURATION=Debug
    - os: osx
      env: FRAMEWORK_VERSION=1.0 CLI_VERSION=1.1.5 CONFIGURATION=Release
    - os: osx
      env: FRAMEWORK_VERSION=2.0 CLI_VERSION=2.0.0 CONFIGURATION=Release
    - os: osx
      env: FRAMEWORK_VERSION=2.0 CLI_VERSION=Latest CONFIGURATION=Debug

install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL "https://dot.net/v1/dotnet-install.sh" | bash /dev/stdin --channel 2.0 --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH" 

before_script:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib; fi
  - dotnet --info
  - if test "$FRAMEWORK_VERSION" == "1.0"; then dotnet restore; fi

script: 
  - dotnet test ./test/Aqua.GraphCompare.Tests/Aqua.GraphCompare.Tests.csproj -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"