image: Visual Studio 2017

branches:
  except:
  - experimental

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

before_build:
  - dotnet --info
  - dotnet restore

build_script:
  - dotnet build src\Aqua.GraphCompare
  - dotnet build test\Aqua.GraphCompare.Tests

test_script:
  - dotnet test test\Aqua.GraphCompare.Tests\Aqua.GraphCompare.Tests.csproj

build:
  verbosity: normal